spring:
  sql:
    init:
      mode: always
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  profiles:
    active: local
    group:
      local: "local, s3"


