cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    s3: #버킷이름
      bucket: ${AWS_S3_BUCKET_NAME}
    region: #S3 지역
      static: ${AWS_S3_REGION}
    stack:
      auto: false