spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
---
spring:
  profiles:
    active: local
    group:
      local: "local, aws"
---

